### ISSUE TITLE
Spotify connector no longer returning artist/track information

### ISSUE THREAD

**Issue by ad1217** [f1u77y/web-media-controller#36]
Controls do still work and I get the current position, but do not get track length, artist, or track name. I'm not sure when this stopped working, rolling back to previous versions of this addon doesn't seem to fix the problem. Other sites (Youtube and Soundcloud) still work as expected.

OS: Arch Linux
Native: wmc-mpris from web-media-controller-mpris-git AUR package, r96.d56d02a
Browser: Firefox 69

**Comment by f1u77y** [comment]
Thanks for your report!

Spotify changed their layout a bit, so we were unable to get art URL, but thanks to awful design of this extension that change have also broken all metadata getters.

Fix from https://github.com/f1u77y/web-media-controller/tree/fix-spotify works for me. Test it if you want, otherwise I'll just merge it to master.

**Comment by ad1217** [comment]
Thanks, that works great!
